apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpnr-api-deployment
  labels:
    app: alpnr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpnr-api
  template:
    metadata:
      labels:
        app: alpnr-api
    spec:
      containers:
      - name: alpnr-api
        image: ghcr.io/punkplod23/fast-alpr-api:latest # Replace with your actual image name and tag
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: alpnr-api-service
spec:
  selector:
    app: alpnr-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alpnr-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: alpnr.localhost # Replace with your actual host name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alpnr-api-service
            port:
              number: 80